// <auto-generated />
using System;
using FindHikingFellow.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FindHikingFellow.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FindHikingFellow.Infrastructure.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "9baea4e0-3afa-4b47-80d3-cfcd4b43e79b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "dd6e608f-2d9b-4517-ae14-5405f550d2df",
                            Email = "organiser@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Organiser",
                            LastName = "First",
                            LockoutEnabled = false,
                            NormalizedEmail = "ORGANISER@GMAIL.COM",
                            NormalizedUserName = "ORGANISER@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEJ7ho+lQtlHt9la12Io8dU0j1rER8bfUe6o47mATaKHPPNggCDECqqWTKdmgKNq4IA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2cda8ed1-782e-408b-8a65-57ec82493feb",
                            TwoFactorEnabled = false,
                            UserName = "organiser@gmail.com"
                        },
                        new
                        {
                            Id = "7d23c6db-4f9c-44c2-8a7d-c4ef9030122d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "30de9f81-4b1d-4e75-99be-ce79c62bcc68",
                            Email = "admin@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Admin",
                            LastName = "First",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAELW4924WerO5gyD4V/3QCt5Khv/7rhuQwyLpx9mml5LjjqTRByBz4qX6uW5JiAMW9w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4e7fe724-3512-41f6-b8c5-ae914f4cc564",
                            TwoFactorEnabled = false,
                            UserName = "admin@gmail.com"
                        },
                        new
                        {
                            Id = "aec4bd2b-913c-425a-936f-8d2bd83c1164",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9dccab79-4f6a-459c-8b33-a66ac4174e52",
                            Email = "participant1@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Participant",
                            LastName = "First",
                            LockoutEnabled = false,
                            NormalizedEmail = "PARTICIPANT1@GMAIL.COM",
                            NormalizedUserName = "PARTICIPANT1@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEFEb28zfYDLofx37DMBpVvyKSn1umZ6crB48b/AeQnzN+V8JaEekSt4xh9Fv59Zsyg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "139119a5-d63d-4ab9-b00d-b267b67a2092",
                            TwoFactorEnabled = false,
                            UserName = "participant1@gmail.com"
                        },
                        new
                        {
                            Id = "480fd4fe-3c32-4626-8ea9-ada588d0d24f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3ec9e82c-3e9c-4545-85a8-4aa2546e8de3",
                            Email = "participant2@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Participant",
                            LastName = "Second",
                            LockoutEnabled = false,
                            NormalizedEmail = "PARTICIPANT2@GMAIL.COM",
                            NormalizedUserName = "PARTICIPANT2@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEN0mfZ83tNLpKMceA+HUx1RwteakckoWm/dGFI0xMz8qsqBE8Tpgd+9gLH0Cd9fh8w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "08e60c0c-3af8-4a3b-842f-14ae5a0f22e5",
                            TwoFactorEnabled = false,
                            UserName = "participant2@gmail.com"
                        });
                });

            modelBuilder.Entity("FindHikingFellow.Infrastructure.Data.Models.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Destinations", (string)null);

                    b.HasComment("Mountain or region that the tour moves through");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://webnews.bg/uploads/images/84/8784/228784/768x432.jpg?_=1460885734",
                            IsDeleted = false,
                            Name = "Pirin"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://vedri.bg/media/fufl535h/national-park-rila-bulgaria.jpg",
                            IsDeleted = false,
                            Name = "Rila"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://trud.bg/public/images/articles/2020-11/mountain-landscape-beautiful-hd-wallpaper-1024x640_1509577115668281610_original.jpg",
                            IsDeleted = false,
                            Name = "Balkan Mauntains"
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "https://bulgariawalking.com/wp-content/uploads/2016/10/rhodopes-and-rila-2.jpg",
                            IsDeleted = false,
                            Name = "Rodopi"
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "https://media-cdn.tripadvisor.com/media/photo-s/1a/d2/6c/b8/caption.jpg",
                            IsDeleted = false,
                            Name = "Vitosha"
                        });
                });

            modelBuilder.Entity("FindHikingFellow.Infrastructure.Data.Models.FeedBack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ActivityType")
                        .HasColumnType("int");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<string>("Review")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("TourId");

                    b.ToTable("FeedBacks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActivityType = 1,
                            AuthorId = "9baea4e0-3afa-4b47-80d3-cfcd4b43e79b",
                            CreatedOn = new DateTime(2023, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 5.0,
                            Review = "Amazing trail. It had snowed the day before and it looked like a winter wonderland. Towards the end, follow the other mountaineers and don’t follow the all trails route. That being said, I didn’t have any snow spikes and the descent was SCARY. Managed to pull through. I even lost my phone on the trial, luckily I had my burner phone with my Bulgarian sim, which is why this journey starts halfway through. Anyway, it is so worth it. Get ready for an adventure almost 9,000 feet up in the Bulgarian mountains",
                            TourId = 2
                        },
                        new
                        {
                            Id = 2,
                            ActivityType = 4,
                            AuthorId = "480fd4fe-3c32-4626-8ea9-ada588d0d24f",
                            CreatedOn = new DateTime(2022, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 5.0,
                            Review = "",
                            TourId = 2
                        });
                });

            modelBuilder.Entity("FindHikingFellow.Infrastructure.Data.Models.KeyPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("KeyPoints", (string)null);

                    b.HasComment("Specific point or place that the tour moves through or near by");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Malyovitsa Hut"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Vihren Hut"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Popovo Lake"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Kazanite"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Koncheto Shelter"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Koncheto"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Vidimsko Praskalo Waterfall"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Yastrebets lift station"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Yontchevo Lake"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Elenino Lake"
                        });
                });

            modelBuilder.Entity("FindHikingFellow.Infrastructure.Data.Models.PersonalList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("PersonalLists", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Completed"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Favourite"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Wish to perform"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Planned"
                        });
                });

            modelBuilder.Entity("FindHikingFellow.Infrastructure.Data.Models.Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ActivityType")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ElevationGain")
                        .HasColumnType("int")
                        .HasComment("The elevation gain in meters");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit")
                        .HasComment("Is tour approved by admin");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<double?>("Length")
                        .HasColumnType("float")
                        .HasComment("The length of the trail in km");

                    b.Property<string>("MeetingPoint")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("The point where the participants are supposed to meet to begin tour");

                    b.Property<DateTime>("MeetingTime")
                        .HasColumnType("datetime2")
                        .HasComment("The time when the participants are supposed to meet to begin tour");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("OrganiserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RouteType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("OrganiserId");

                    b.ToTable("Tours", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActivityType = 1,
                            Description = "Let's enjoy together this trail near Bansko, Blagoevgrad. Generally considered a challenging route, this is a very popular area for hiking.",
                            DestinationId = 1,
                            Difficulty = 3,
                            Duration = "About 6 hours inlucding breaks for pictures and a lunch break",
                            ElevationGain = 931,
                            ImageUrl = "https://www.datocms-assets.com/55179/1647278287-screen-shot-2019-07-22-at-7-13-00-am.png",
                            IsApproved = false,
                            IsDeleted = false,
                            Length = 8.5,
                            MeetingPoint = "Vihren hut",
                            MeetingTime = new DateTime(2024, 8, 13, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Vihren Peak",
                            OrganiserId = "9baea4e0-3afa-4b47-80d3-cfcd4b43e79b",
                            RouteType = 2
                        },
                        new
                        {
                            Id = 2,
                            ActivityType = 1,
                            Description = "Very scenic and beautiful hiking. Dramatic cliffs, lakes and stunning views from the summit. Big part of the trail is very rocky so use stable hiking shoes. It’s physically demanding but an amaizing one. There is lots of water so no need to bring extra.",
                            DestinationId = 2,
                            Difficulty = 3,
                            Duration = "About 7 hours inlucding breaks for pictures and a lunch break",
                            ElevationGain = 1017,
                            ImageUrl = "https://novavarna.net/wp-content/uploads/2020/06/rila_maliovica-1280x720.jpg",
                            IsApproved = false,
                            IsDeleted = false,
                            Length = 15.9,
                            MeetingPoint = "Malyovitsa hotel",
                            MeetingTime = new DateTime(2024, 7, 25, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Malyovitsa Peak",
                            OrganiserId = "9baea4e0-3afa-4b47-80d3-cfcd4b43e79b",
                            RouteType = 2
                        });
                });

            modelBuilder.Entity("FindHikingFellow.Infrastructure.Data.Models.TourKeyPoint", b =>
                {
                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.Property<int>("KeyPointId")
                        .HasColumnType("int");

                    b.HasKey("TourId", "KeyPointId");

                    b.HasIndex("KeyPointId");

                    b.ToTable("TourKeyPoints", (string)null);

                    b.HasData(
                        new
                        {
                            TourId = 2,
                            KeyPointId = 1
                        },
                        new
                        {
                            TourId = 2,
                            KeyPointId = 10
                        });
                });

            modelBuilder.Entity("FindHikingFellow.Infrastructure.Data.Models.TourParticipant", b =>
                {
                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.Property<string>("ParticipantId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TourId", "ParticipantId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("TourParticipants", (string)null);

                    b.HasData(
                        new
                        {
                            TourId = 2,
                            ParticipantId = "aec4bd2b-913c-425a-936f-8d2bd83c1164"
                        });
                });

            modelBuilder.Entity("FindHikingFellow.Infrastructure.Data.Models.TourPersonalList", b =>
                {
                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.Property<int>("PersonalListId")
                        .HasColumnType("int");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TourId", "PersonalListId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PersonalListId");

                    b.ToTable("TourPersonalLists", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimType = "user:fullname",
                            ClaimValue = "Organiser First",
                            UserId = "9baea4e0-3afa-4b47-80d3-cfcd4b43e79b"
                        },
                        new
                        {
                            Id = 2,
                            ClaimType = "user:fullname",
                            ClaimValue = "Admin First",
                            UserId = "7d23c6db-4f9c-44c2-8a7d-c4ef9030122d"
                        },
                        new
                        {
                            Id = 3,
                            ClaimType = "user:fullname",
                            ClaimValue = "Participant First",
                            UserId = "aec4bd2b-913c-425a-936f-8d2bd83c1164"
                        },
                        new
                        {
                            Id = 4,
                            ClaimType = "user:fullname",
                            ClaimValue = "Participant Second",
                            UserId = "480fd4fe-3c32-4626-8ea9-ada588d0d24f"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FindHikingFellow.Infrastructure.Data.Models.FeedBack", b =>
                {
                    b.HasOne("FindHikingFellow.Infrastructure.Data.Models.ApplicationUser", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FindHikingFellow.Infrastructure.Data.Models.Tour", "Tour")
                        .WithMany("FeedBacks")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("FindHikingFellow.Infrastructure.Data.Models.Tour", b =>
                {
                    b.HasOne("FindHikingFellow.Infrastructure.Data.Models.Destination", "Destination")
                        .WithMany("Tours")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FindHikingFellow.Infrastructure.Data.Models.ApplicationUser", "Organiser")
                        .WithMany()
                        .HasForeignKey("OrganiserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Organiser");
                });

            modelBuilder.Entity("FindHikingFellow.Infrastructure.Data.Models.TourKeyPoint", b =>
                {
                    b.HasOne("FindHikingFellow.Infrastructure.Data.Models.KeyPoint", "KeyPoint")
                        .WithMany("Tours")
                        .HasForeignKey("KeyPointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FindHikingFellow.Infrastructure.Data.Models.Tour", "Tour")
                        .WithMany("KeyPoints")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KeyPoint");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("FindHikingFellow.Infrastructure.Data.Models.TourParticipant", b =>
                {
                    b.HasOne("FindHikingFellow.Infrastructure.Data.Models.ApplicationUser", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FindHikingFellow.Infrastructure.Data.Models.Tour", "Tour")
                        .WithMany("Participants")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Participant");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("FindHikingFellow.Infrastructure.Data.Models.TourPersonalList", b =>
                {
                    b.HasOne("FindHikingFellow.Infrastructure.Data.Models.ApplicationUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FindHikingFellow.Infrastructure.Data.Models.PersonalList", "PersonalList")
                        .WithMany("Tours")
                        .HasForeignKey("PersonalListId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FindHikingFellow.Infrastructure.Data.Models.Tour", "Tour")
                        .WithMany("PersonalLists")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("PersonalList");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FindHikingFellow.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FindHikingFellow.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FindHikingFellow.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FindHikingFellow.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FindHikingFellow.Infrastructure.Data.Models.Destination", b =>
                {
                    b.Navigation("Tours");
                });

            modelBuilder.Entity("FindHikingFellow.Infrastructure.Data.Models.KeyPoint", b =>
                {
                    b.Navigation("Tours");
                });

            modelBuilder.Entity("FindHikingFellow.Infrastructure.Data.Models.PersonalList", b =>
                {
                    b.Navigation("Tours");
                });

            modelBuilder.Entity("FindHikingFellow.Infrastructure.Data.Models.Tour", b =>
                {
                    b.Navigation("FeedBacks");

                    b.Navigation("KeyPoints");

                    b.Navigation("Participants");

                    b.Navigation("PersonalLists");
                });
#pragma warning restore 612, 618
        }
    }
}
